# This script checks if the 'inflect' library is installed and prints a message inflict is working
import inflect
print("inflect is working")
# inflect.engine is initiated to use the inflect library for generating articles
p=inflect.engine()
print("---------------------------------------------------------------------")
print("\n***This is a input script that collects words used to generate a story***")
person = input("Enter a person's name: ")
gender = input("Enter Gender (male or female): ").lower()
day = input("Enter a day from Monday to Friday: ")
transport = p.a(input("Enter a transport vehicle: "))
am_time = input("Enter a number less than or equal to 12 (for AM): ")
sound = input("Name one frightening sound: ")
verb = input("Enter a vocal action verb in past tense: ")
plural_noun = input("Enter a plural noun for a group of people: ")
exclamation_word = input("Enter a word that expresses surprise: ")
minutes_time = int(input("Enter a number to represent an emergency time: "))

# check if the number inputed in minutes_time is less than 11 so it can display a text "few".
# And if number is greater than 11 it prints the number of minutes.
# But if the number is 0 it prints "Zero"
if minutes_time < 11 and minutes_time > 1:
    minutes_time = "few"
elif minutes_time == 0 or minutes_time == 1:
    minutes_time = "a"
else:
    print("minutes_time")


# Pronoun selection that helps to determine the correct pronoun to be used in the sentence.
if gender == "male":
    pronoun = "his"
    personal_pronoun = "he"
elif gender == "female":
    pronoun = "her"              
    personal_pronoun = "she"
else:
    pronoun = "his"
    personal_pronoun = "he"

    
# This is the final story that will be generated using the inputs provided by the user.
# It uses the inputs to create a narrative that includes the person's name, the day of the week, the transport they took, the time, and other details.
print("---------------------------------------------------------------------")
print("*********MAD LIBS STORY***********")
mad_libs_story = f"""{person.capitalize()} booked a ride on {day.lower()}, hoping to catch {transport} leaving at around {am_time}am in the morning.
As {person.capitalize()} arrived at {pronoun} destination, {personal_pronoun} heared {sound.lower()} in the distance.
Startled, {person.capitalize()} {verb.lower()} "{exclamation_word.capitalize()}!" and looked for a security officer. The {plural_noun.lower()} around began to panic.
Within {minutes_time} minutes, security staff secured the area and confirmed it was a false alarm.
Relieved but shaken, {person.capitalize()} walked patiently to exit the place."""

# This prints the final story generated by the inputs provided by the user.
print(mad_libs_story)
print("---------------------------------------------------------------------")
